version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: logitrack-prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api
    networks:
      - logitrack-network

  alertmanager:
        image: prom/alertmanager:latest
        container_name: logitrack-alertmanager
        restart: always
        ports:
          - "9093:9093"
        networks:
          - logitrack-network


  grafana:
    image: grafana/grafana:latest
    container_name: logitrack-grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - logitrack-network

  loki:
    image: grafana/loki:latest
    container_name: logitrack-loki
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - logitrack-network

  promtail:
    image: grafana/promtail:latest
    container_name: logitrack-promtail
    user: root
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - logitrack-network

  mysqldb:
    image: mysql:8.0
    container_name: logitrack-mysql
    restart: always
    environment:
      MYSQL_DATABASE: logitrack_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - logitrack-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: logitrack-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/logitrack_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_FLYWAY_ENABLED: "true"
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - logitrack-network

networks:
  logitrack-network:
    driver: bridge